#Scaling Parameters
hpa:
  enabled: true
  targetCPUUtilizationPercentage: 70
  TargetAvgMemoryUtilization: 70
replicaCount: 1
maxReplicas: 1

## Resource Limits ##
resources:
 limits:
   cpu: "2"
   memory: 2Gi
 requests:
   cpu: "200m"
   memory: 1Gi

## Ingress Configuration ##
ingress_internal:
  enabled: true
  hosts:
    ems-v1-script-js.tajawal-dev.internal:
      - /

## Envrionemnt Variables and configmap"
environment_variable:
  enabled: true
  data:
    APP : "ems-v1-script-js-dev"
    LOG_LEVEL: "info"
    LOG_FORMAT: "json"
    API_HTTP_PORT: "7001"
    API_ENV: "dev"