#Scaling Parameters
hpa:
  enabled: true
  targetCPUUtilizationPercentage: 70
  TargetAvgMemoryUtilization: 70
replicaCount: 2
maxReplicas: 10

## Resource Limits ##
resources:
 limits:
   cpu: "4"
   memory: 4Gi
 requests:
   cpu: "0.5"
   memory: "2Gi"

## Ingress Configuration ##
ingress_internal:
  enabled: true
  hosts:
    ems-script-js.tajawal-prod-apps.internal:
      - /

## Envrionemnt Variables and configmap"
environment_variable:
  enabled: true
  data:
    APP : "ems-script-js-prod-apps"
    LOG_LEVEL: "info"
    LOG_FORMAT: "json"
    API_HTTP_PORT: "80"
    API_ENV: "live"

